name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: update-tokens
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.client_payload.tokenFilePath }}
          json: ${{ github.event.client_payload.tokens }}
    #  - name: Use Node.js 14.x
    #    uses: actions/setup-node@v1
    #    with:
    #     node-version: 14.x
      - name: Deploy
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
