name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: do-something
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
         version: 10.x
      - name: Do Something
        run: echo Doing Something...
      - name: Do Something Based On Triggered Event Data
        run: 'echo "Triggered event text: ${{ github.event.client_payload.text }}"'
      - name: Write file
        run: 'echo "Triggered event text: ${{ github.event.client_payload.text }}" >> test.txt'
# THIS IS WHERE THE DATA IS PUBLISHED TO A BRANCH
      - name: Deploy
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main' #optional defaults to master
